### ISSUE TITLE
Create a versioned SDK to create tasks, samples, and check the environment

### ISSUE THREAD

**Issue by sirdarckcat** [google/kctf#158]
it would be cool if ppl just had to do: `tar xzf kctf.dev/kctf-1.0.0.tgz && cd kctf-1.0.0`, the SDK can contain all its build-time dependencies packaged up (currently its only `yq`), although in the future it could include more things. this is necessary for versioning.

an alternative to tar would be to have the SDK be a Docker image, and people would run `docker run gcr.io/kctf/sdk:1.0.0 -V "$PWD" command` or something like that to limit the number of dependencies to just docker (and maybe kind)

 - [ ] SDK should check if environment is OK (see #100), that all deps are installed and are compatible (see #6)
 - [x] SDK should copy a sample, not a challenge-skelleton (see #15)
 - [ ] SDK should be compatible among major versions (vMAJOR.MINOR.PATCH) so upgrades are transparent (see #5)

**Comment by sirdarckcat** [comment]
#6

**Comment by sirdarckcat** [comment]
#15

**Comment by sirdarckcat** [comment]
#5

**Comment by sirdarckcat** [comment]
#100

**Comment by sroettger** [comment]
So this could be a single binary that does everything with subcommands similar to how gcloud works.

For example:
```sh
kctf cluster start
kctf challenge build
```

**Comment by sroettger** [comment]
Should the SDK be always installed inside the ctf directory? That way, we can avoid the issue of multiple authors using incompatible versions.
Would this be enough to solve all versioning issues?

**Comment by sroettger** [comment]
So you could install a global kctf binary that only has two jobs:
1) download a kctf sdk version and install it to the challenge directory (it could check available versions and prompt the user, or have a choice between stable / beta)
2) whenever you run a different command, it can traverse the current directory up and check if there's a kctf-conf/sdk/kctf somewhere. If it exists, run that instead. If it doesn't, complain that you need to be in the challenge directory.

**Comment by sirdarckcat** [comment]
this is done, right?

I guess we aren't checking dependencies and umask at startup though, are we?

**Comment by sroettger** [comment]
We don't do that yet.
What do we need? Just gcloud, kubectl and docker right? And gcloud should only be needed when interacting with a real cluster.

**Comment by sirdarckcat** [comment]
yep, just kubectl and docker as required, and gcloud as a warning/notice.
